### ISSUE TITLE
Making sense of the related langs

### ISSUE THREAD

**Issue by ghost** [droher/etymology-db#6]
Thanks for extracting all this data! I've been investigating the formation of German compounds. However, I'm confused by the related_lang fields. e.g.

```
term_id,lang,term,reltype,related_term_id,related_lang,related_term,position,group_tag,parent_tag,parent_position
ualTS6tTUg2mdZtsSJV-Lw, German, wahrscheinlich, compound_of, 79PzrNZxUaqTC9uOjKOtsQ, Yangum Dey, wahr, 0, , , 
ualTS6tTUg2mdZtsSJV-Lw, German, wahrscheinlich, compound_of, EPBI80uLWHGxYzTpI7ICCw, Yangum Dey, scheinen, 1, , , 
ualTS6tTUg2mdZtsSJV-Lw, German, wahrscheinlich, compound_of, v6mhJCsCVRSysICgubOQbg, Yangum Dey, -lich, 2, , , 
```

I'm not sure where the "Yangum Dey" comes from. The wiktionary pages for those three don't mention that language. What does it mean there?

**Comment by IraqCanada** [comment]
Hey there, I think the issue mentioned here is a result of the wiktionary_codes file being incorrect. The 2-digit codes are correct, but the 3-digit codes are all being read as 2-digit codes, which means that there is accidental overlap between languages. eg. latin has wiktionary code la and Yaul has wiktionary code yla, but since the first letter of 3 letter codes is being cut off, yaul's code is being stored as la, so all of the latin related terms are listed as Yaul instead of latin.

**Comment by IraqCanada** [comment]
Hey there, I think the issue mentioned here is a result of the wiktionary_codes file being incorrect. The 2-digit codes are correct, but the 3-digit codes are all being read as 2-digit codes, which means that there is accidental overlap between languages. eg. latin has wiktionary code la and Yaul has wiktionary code yla, but since the first letter of 3 letter codes is being cut off, yaul's code is being stored as la, so all of the latin related terms are listed as Yaul instead of latin.

**Comment by droher** [comment]
Thanks for catching this! I've updated the data/code with the fix.
